### ISSUE TITLE
Icon colors using mask do not work on Chrome

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/website#1]
Using:

```css
mask: url("../svg/check.svg");
background: var(--std-color);
mask-size: cover;
```

Works fine in Firefox, but just shows boxes in Chrome (`Version 87.0.4280.88 (Official Build) (64-bit)`).

@chrism, I just want to change the icon color based on `prefers-color-scheme` do you know a more compatible way to achieve this without resorting to different colored SVG files?

**Comment by tmpfs** [comment]
Using `background-image` with `filter` does the trick:

```css
.icon {
  display: inline-block;
  width: 24px;
  height: 24px;
  filter: var(--std-color-filter);
  background-size: cover;
}

.icon-menu {
  background-image: url(../svg/menu.svg);
}
```

We switch the `--std-color-filter` variable depending upon `prefers-color-scheme`.
